### ISSUE TITLE
Modular polearms can't be gilded

### ISSUE THREAD

**Issue by AlbusRex** [AceTheEldritchKing/Secrets-Of-Forging-Revelations#1]
The title is pretty clear, it is not possible to gild a modular polearm.

![image](https://github.com/AceTheEldritchKing/Secrets-Of-Forging-Revelations/assets/69213368/6f6f65e1-8365-4fef-be00-5264c390a7bf)

## Version

Using latest available versions for Tetra, AoF and SoFR for forge 1.19.2

- Forge: 43.2.21 for MC 1.19.2
- Tetra: 5.4.0
- AoF: 1.6.7
- SoFR: 1.2.1

## Steps to reproduce:

1. Craft an iron spear or any other modular polearm.
2. Hone the modular polearm manually or with the tetra command.
3. Place a workstation, a gilding scroll on top of said workstation and a have hammer on the inventory.
4. Observe that gilding is not on the honing upgrades list, like in the provided picture.

### Observations

With my very limited knowledge I attempted to diagnose the issue, and I think it might have something to do with modular polearms not being in the list of items that 'data/tetra/improvements/shared' applies to from Tetra itself. This list includes the gilding improvement among others.
I hope this issue has all the relevant information to fix this and thank you for maintaining this excelent mod.

**Comment by AlbusRex** [comment]
I have figured out a fix for this issue, there is an open [PR](https://github.com/AceTheEldritchKing/Secrets-Of-Forging-Revelations/pull/2) with the fix I made.

**Comment by AceTheEldritchKing** [comment]
Hi! I already found the issue and fixed it on the main branch. The fix will be available next update, as right now there are other additions in the main branch that haven't been pushed as well.

**Comment by AlbusRex** [comment]
I see, I will mark this issue as closed and cancel the PR as well since there is a confirmed fix.
I am looking forward to the next update :)
