### ISSUE TITLE
Some probblem with 1.20

### ISSUE THREAD

**Issue by anechooyo** [AceTheEldritchKing/Secrets-Of-Forging-Revelations#5]
Hi,I'm using your code as an example for my onw project.
but as a beginner,I meet some problem.
exactly,at net.acetheeldritchking.item.ModularPolearm, line 102, "allowedIn" is not work at version 1.20.1,could you please give me some suggestion?

**Comment by AceTheEldritchKing** [comment]
Hello, I'm actually not very familiar with Tetra for 1.20.1 since it is closed source. I recommend you look at the code for Tetra through your IDE, specifically how the hammers are added to the creative menu. Good luck!

**Comment by anechooyo** [comment]
OK,thank you very much!
